sudo: false
language: node_js

cache:
  directories:
    - node_modules
    
notifications:
  email:
    on_success: never
    on_failure: change

install:
  - npm install

script:
  - npm test

branches:
  only:
    - master