sudo: false
language: node_js

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@^3.0.0

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - npm install

script:
  - npm test

branches:
  only:
    - master